//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponderManagement.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int hisoryId { get; set; }
        public Nullable<System.DateTime> emailDate { get; set; }
        public byte[] time { get; set; }
        public string emergency { get; set; }
        public string comments { get; set; }
        public string streetAddress { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<int> zipcode { get; set; }
    }
}
